<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Collection;
use App\Models\Product;
use App\Models\ProductImage;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            // ── Ceramics & Glassware (product-01 to product-04) ──────
            [
                'name' => 'Vintage Ceramic Vase',
                'slug' => 'vintage-ceramic-vase',
                'description' => 'A beautifully aged ceramic vase with subtle hand-painted floral motifs. This piece has graced a family home for decades, carrying the warmth of shared meals and quiet evenings. The glaze shows gentle signs of age that only add to its charm. Perfect as a standalone decorative piece or filled with fresh or dried flowers.',
                'short_description' => 'A beautifully aged ceramic vase with hand-painted floral motifs — a treasured find from a family home.',
                'price' => 45.00,
                'sku' => 'NORA-CER-001',
                'stock_quantity' => 1,
                'origin_type' => 'other',
                'origin_country' => 'Middle East (estimated)',
                'artisan_name' => null,
                'product_story' => 'This vase was part of a private collection for over thirty years. It was originally purchased from a local ceramics market and has been carefully displayed in a living room, never used for water — only admired.',
                'materials_used' => 'Stoneware clay, hand-applied glaze',
                'handmade_technique' => 'Hand-thrown and hand-painted',
                'care_instructions' => 'Display only. Wipe gently with a soft, dry cloth. Not suitable for water unless confirmed watertight.',
                'estimated_preparation_time' => '1-2 days',
                'estimated_shipping_time' => '7-14 business days',
                'is_one_of_a_kind' => true,
                'gift_wrapping_available' => true,
                'is_featured' => true,
                'cultural_note' => 'Ceramic artistry has deep roots across the Middle East, with techniques passed down through generations of potters.',
                'dimensions' => 'Approx. 25cm H × 15cm W',
                'weight' => 0.85,
                'color_palette' => 'Warm cream, terracotta, sage green accents',
                'color_primary' => 'Cream',
                'color_secondary' => 'Terracotta',
                'condition' => 'Good — minor glaze crazing consistent with age',
                'age_estimate' => 'Mid-20th century (estimated)',
                'style_notes' => 'Traditional thrown form with hand-painted floral motifs',
                'height_cm' => 25,
                'width_cm' => 15,
                'depth_cm' => 15,
                'categories' => ['ceramics-glassware'],
                'collections' => ['gifts-with-a-story'],
                'image_path' => 'images/nora/products/product-01.jpeg',
            ],
            [
                'name' => 'Hand-Painted Decorative Bowl',
                'slug' => 'hand-painted-decorative-bowl',
                'description' => 'A charming decorative bowl featuring hand-painted patterns in earthy tones. The brushwork reveals the hand of its maker — no two strokes identical. A lovely piece for displaying fruit, keys, or simply sitting on a shelf as a quiet work of art.',
                'short_description' => 'A charming hand-painted decorative bowl in warm earthy tones.',
                'price' => 38.00,
                'sku' => 'NORA-CER-002',
                'stock_quantity' => 1,
                'origin_type' => 'other',
                'origin_country' => 'Middle East (estimated)',
                'artisan_name' => null,
                'product_story' => 'Found in an estate sale, this bowl was one of several pieces from a collector who appreciated handmade ceramics. Its gentle wear speaks of years of quiet appreciation.',
                'materials_used' => 'Ceramic clay, mineral-based paints',
                'handmade_technique' => 'Hand-painted with natural brushes',
                'care_instructions' => 'Hand wash gently. Not recommended for food use unless confirmed food-safe.',
                'estimated_preparation_time' => '1-2 days',
                'estimated_shipping_time' => '7-14 business days',
                'is_one_of_a_kind' => true,
                'gift_wrapping_available' => true,
                'is_featured' => false,
                'dimensions' => 'Approx. 20cm Ø × 8cm H',
                'weight' => 0.55,
                'color_palette' => 'Warm terracotta, cream, ochre, forest green',
                'color_primary' => 'Terracotta',
                'color_secondary' => 'Ochre',
                'condition' => 'Good — light surface wear on base',
                'age_estimate' => 'Late 20th century (estimated)',
                'style_notes' => 'Organic form with brushwork visible in patterns',
                'height_cm' => 8,
                'width_cm' => 20,
                'depth_cm' => 20,
                'categories' => ['ceramics-glassware'],
                'collections' => [],
                'image_path' => 'images/nora/products/product-02.jpeg',
            ],
            [
                'name' => 'Ornate Decorative Plate',
                'slug' => 'ornate-decorative-plate',
                'description' => 'An ornate decorative plate with intricate border patterns and a rich colour palette. This commemorative-style piece was designed to be admired, not used. A beautiful addition to a plate wall or displayed on a stand.',
                'short_description' => 'An ornate decorative plate with intricate border patterns — a collector\'s piece.',
                'price' => 52.00,
                'sku' => 'NORA-CER-003',
                'stock_quantity' => 1,
                'origin_type' => 'other',
                'origin_country' => 'Middle East (estimated)',
                'artisan_name' => null,
                'product_story' => 'This plate was part of a commemorative collection. Its detailed patterns suggest it was crafted to celebrate a special occasion or heritage.',
                'materials_used' => 'Fine ceramic, decorative glaze',
                'handmade_technique' => 'Moulded and hand-finished',
                'care_instructions' => 'Display only. Dust with a soft cloth.',
                'estimated_preparation_time' => '1-2 days',
                'estimated_shipping_time' => '7-14 business days',
                'is_one_of_a_kind' => true,
                'gift_wrapping_available' => true,
                'is_featured' => true,
                'dimensions' => 'Approx. 28cm Ø × 3cm H',
                'weight' => 0.65,
                'color_palette' => 'Deep navy, gold, ivory, burgundy accents',
                'color_primary' => 'Navy',
                'color_secondary' => 'Gold',
                'condition' => 'Excellent — minimal wear, vibrant colours',
                'age_estimate' => 'Commemorative style, modern era',
                'style_notes' => 'Ornate border with geometric and floral motifs',
                'height_cm' => 3,
                'width_cm' => 28,
                'depth_cm' => 28,
                'categories' => ['ceramics-glassware'],
                'collections' => ['gifts-with-a-story'],
                'image_path' => 'images/nora/products/product-03.jpeg',
            ],
            [
                'name' => 'Heritage Glassware Set',
                'slug' => 'heritage-glassware-set',
                'description' => 'A set of vintage glassware with a subtle etched design. These glasses have been part of a family\'s entertaining collection, used for special gatherings and holiday meals. The glass has a lovely weight and clarity that modern reproductions rarely achieve.',
                'short_description' => 'Vintage etched glassware — once part of a family\'s cherished entertaining collection.',
                'price' => 35.00,
                'sku' => 'NORA-CER-004',
                'stock_quantity' => 4,
                'origin_type' => 'other',
                'origin_country' => 'Middle East (estimated)',
                'artisan_name' => null,
                'product_story' => 'These glasses were brought out only for special occasions. Their careful preservation over the years means they remain in excellent condition.',
                'materials_used' => 'Pressed glass with etched detail',
                'handmade_technique' => 'Machine-pressed, hand-etched',
                'care_instructions' => 'Hand wash gently. Avoid thermal shock.',
                'estimated_preparation_time' => '1-2 days',
                'estimated_shipping_time' => '7-14 business days',
                'is_one_of_a_kind' => false,
                'gift_wrapping_available' => true,
                'is_featured' => false,
                'dimensions' => 'Approx. 10cm Ø × 12cm H each',
                'weight' => 0.35,
                'color_palette' => 'Clear glass with frosted etched details',
                'color_primary' => 'Clear',
                'color_secondary' => 'Frosted',
                'condition' => 'Very good — no chips or cracks visible',
                'age_estimate' => 'Mid-20th century (estimated)',
                'style_notes' => 'Classic pressed glass form with delicate etched banding',
                'height_cm' => 12,
                'width_cm' => 10,
                'depth_cm' => 10,
                'categories' => ['ceramics-glassware'],
                'collections' => [],
                'image_path' => 'images/nora/products/product-04.jpeg',
            ],

            // ── Decorative Objects & Art (product-05 to product-08) ──
            [
                'name' => 'Handmade Folk Art Doll',
                'slug' => 'handmade-folk-art-doll',
                'description' => 'A charming handmade folk doll dressed in traditional textiles. Each stitch was placed with care, reflecting the folk art traditions of the region. This doll is a wonderful collector\'s item or a meaningful gift that carries the spirit of handmade heritage.',
                'short_description' => 'A charming handmade folk doll dressed in traditional textiles — a piece of living heritage.',
                'price' => 42.00,
                'sku' => 'NORA-DEC-005',
                'stock_quantity' => 1,
                'origin_type' => 'other',
                'origin_country' => 'Middle East (estimated)',
                'artisan_name' => null,
                'product_story' => 'Folk dolls like this have been made by hand for generations, each one unique to the maker\'s style and the textiles available to them.',
                'materials_used' => 'Cotton fabric, wool yarn, natural dyes, stuffing',
                'handmade_technique' => 'Hand-sewn and hand-dressed',
                'care_instructions' => 'Display only. Keep away from direct sunlight to preserve fabric colours.',
                'estimated_preparation_time' => '1-2 days',
                'estimated_shipping_time' => '7-14 business days',
                'is_one_of_a_kind' => true,
                'gift_wrapping_available' => true,
                'is_featured' => true,
                'cultural_note' => 'Folk dolls are a traditional craft in many cultures, often made by mothers and grandmothers as toys or protective charms for children.',
                'dimensions' => 'Approx. 28cm H × 10cm W',
                'weight' => 0.15,
                'color_palette' => 'Cream, deep red, navy blue, olive green',
                'color_primary' => 'Cream',
                'color_secondary' => 'Deep Red',
                'condition' => 'Good — handmade irregularities are part of charm',
                'age_estimate' => 'Traditional craft style',
                'style_notes' => 'Hand-sewn with traditional textile patterns, embroidered details',
                'height_cm' => 28,
                'width_cm' => 10,
                'depth_cm' => 5,
                'categories' => ['decorative-objects-art'],
                'collections' => ['gifts-with-a-story'],
                'image_path' => 'images/nora/products/product-05.jpeg',
            ],
            [
                'name' => 'Decorative Artistic Figurine',
                'slug' => 'decorative-artistic-figurine',
                'description' => 'A small decorative figurine with an artistic, sculptural quality. Its form suggests movement and grace, making it a captivating piece for a shelf, desk, or mantelpiece. A lovely example of decorative art that transcends categories.',
                'short_description' => 'A small decorative figurine with sculptural grace — a captivating art piece.',
                'price' => 28.00,
                'sku' => 'NORA-DEC-006',
                'stock_quantity' => 1,
                'origin_type' => 'other',
                'origin_country' => 'Middle East (estimated)',
                'artisan_name' => null,
                'product_story' => 'This figurine was found among a collection of decorative objects. Its artistic quality suggests it was made by someone with a keen eye for form.',
                'materials_used' => 'Ceramic or resin composite',
                'handmade_technique' => 'Sculpted and finished by hand',
                'care_instructions' => 'Dust gently with a soft cloth. Handle with care.',
                'estimated_preparation_time' => '1-2 days',
                'estimated_shipping_time' => '7-14 business days',
                'is_one_of_a_kind' => true,
                'gift_wrapping_available' => true,
                'is_featured' => false,
                'dimensions' => 'Approx. 18cm H × 8cm W',
                'weight' => 0.40,
                'color_palette' => 'Matte white, subtle grey shadows',
                'color_primary' => 'White',
                'color_secondary' => 'Grey',
                'condition' => 'Excellent — clean surfaces, no damage',
                'age_estimate' => 'Modern decorative piece',
                'style_notes' => 'Sculptural flowing form suggesting human movement',
                'height_cm' => 18,
                'width_cm' => 8,
                'depth_cm' => 8,
                'categories' => ['decorative-objects-art'],
                'collections' => [],
                'image_path' => 'images/nora/products/product-06.jpeg',
            ],
            [
                'name' => 'Vintage Artistic Mirror',
                'slug' => 'vintage-artistic-mirror',
                'description' => 'A vintage decorative mirror with an ornate frame. The frame shows beautiful patina and character developed over years of display. A statement piece that adds depth and light to any room while carrying the quiet elegance of a bygone era.',
                'short_description' => 'A vintage decorative mirror with an ornate frame and beautiful patina.',
                'price' => 65.00,
                'sku' => 'NORA-DEC-007',
                'stock_quantity' => 1,
                'origin_type' => 'other',
                'origin_country' => 'Middle East (estimated)',
                'artisan_name' => null,
                'product_story' => 'This mirror hung in a hallway for many years, reflecting daily life and special occasions alike. Its frame has aged gracefully, developing a character that new pieces simply cannot replicate.',
                'materials_used' => 'Glass mirror, ornate frame (wood or resin)',
                'handmade_technique' => 'Frame hand-finished',
                'care_instructions' => 'Clean mirror with glass cleaner. Dust frame gently.',
                'estimated_preparation_time' => '1-2 days',
                'estimated_shipping_time' => '7-14 business days',
                'is_one_of_a_kind' => true,
                'gift_wrapping_available' => true,
                'is_featured' => true,
                'dimensions' => 'Approx. 45cm H × 35cm W',
                'weight' => 1.80,
                'color_palette' => 'Antique gold frame, clear mirror, patina details',
                'color_primary' => 'Gold',
                'color_secondary' => 'Antique',
                'condition' => 'Good — beautiful patina, mirror clear',
                'age_estimate' => 'Late 20th century (estimated)',
                'style_notes' => 'Ornate carved frame with scrolling acanthus details',
                'height_cm' => 45,
                'width_cm' => 35,
                'depth_cm' => 3,
                'categories' => ['decorative-objects-art'],
                'collections' => ['handcrafted-home-decor'],
                'image_path' => 'images/nora/products/product-07.jpeg',
            ],
            [
                'name' => 'Cultural Wall Art Panel',
                'slug' => 'cultural-wall-art-panel',
                'description' => 'A cultural wall art panel featuring motifs and patterns that speak to heritage and tradition. Whether it depicts a landscape, geometric design, or cultural scene, this piece adds meaning and beauty to any wall. A wonderful conversation starter.',
                'short_description' => 'A cultural wall art panel rich with heritage motifs and traditional patterns.',
                'price' => 55.00,
                'sku' => 'NORA-DEC-008',
                'stock_quantity' => 1,
                'origin_type' => 'other',
                'origin_country' => 'Middle East (estimated)',
                'artisan_name' => null,
                'product_story' => 'Wall art panels like this serve as windows into cultural memory. This piece was chosen for the story it tells and the beauty it carries.',
                'materials_used' => 'Printed or painted panel, frame',
                'handmade_technique' => 'Hand-finished framing',
                'care_instructions' => 'Hang away from direct sunlight. Dust gently.',
                'estimated_preparation_time' => '1-2 days',
                'estimated_shipping_time' => '7-14 business days',
                'is_one_of_a_kind' => true,
                'gift_wrapping_available' => true,
                'is_featured' => false,
                'dimensions' => 'Approx. 40cm H × 30cm W',
                'weight' => 0.90,
                'color_palette' => 'Rich earth tones, deep browns, warm gold',
                'color_primary' => 'Brown',
                'color_secondary' => 'Gold',
                'condition' => 'Good — colours well preserved',
                'age_estimate' => 'Cultural art piece',
                'style_notes' => 'Detailed scene with cultural motifs and heritage patterns',
                'height_cm' => 40,
                'width_cm' => 30,
                'depth_cm' => 2,
                'categories' => ['decorative-objects-art'],
                'collections' => ['gifts-with-a-story'],
                'image_path' => 'images/nora/products/product-08.jpeg',
            ],

            // ── Watches & Jewellery (product-09 to product-11) ───────
            [
                'name' => 'Vintage Timepiece',
                'slug' => 'vintage-timepiece',
                'description' => 'A classic vintage watch that has kept time through decades of daily wear. The dial shows a gentle patina that collectors treasure, and the mechanism still keeps reasonable time. A wearable piece of history — a reminder that beautiful things only grow more meaningful with age.',
                'short_description' => 'A classic vintage watch with a patina dial — wearable history that only grows more meaningful.',
                'price' => 85.00,
                'sku' => 'NORA-JWL-009',
                'stock_quantity' => 1,
                'origin_type' => 'other',
                'origin_country' => 'Middle East (estimated)',
                'artisan_name' => null,
                'product_story' => 'This watch was worn daily by its previous owner for many years. The scratches on the case and the warmth of the patina tell the story of a life well-lived.',
                'materials_used' => 'Stainless steel case, leather strap, glass crystal',
                'handmade_technique' => 'Manufactured movement, hand-assembled',
                'care_instructions' => 'Keep away from water. Wind gently if mechanical. Store in a dry place.',
                'estimated_preparation_time' => '1-2 days',
                'estimated_shipping_time' => '7-14 business days',
                'is_one_of_a_kind' => true,
                'gift_wrapping_available' => true,
                'is_featured' => true,
                'cultural_note' => 'Vintage watches are increasingly collectible. The patina and wear marks are considered signs of authenticity and character, not defects.',
                'dimensions' => 'Approx. 36mm case Ø, 18cm total length',
                'weight' => 0.08,
                'color_palette' => 'Silver-tone case, warm patina dial, brown leather',
                'color_primary' => 'Silver',
                'color_secondary' => 'Brown',
                'condition' => 'Good — patina dial, keeps approximate time',
                'age_estimate' => 'Mid-20th century (estimated)',
                'style_notes' => 'Classic round case with aged leather strap',
                'height_cm' => 4,
                'width_cm' => 4,
                'depth_cm' => 1,
                'categories' => ['watches-jewellery'],
                'collections' => ['gifts-with-a-story'],
                'image_path' => 'images/nora/products/product-09.jpeg',
            ],
            [
                'name' => 'Heritage Necklace',
                'slug' => 'heritage-necklace',
                'description' => 'A beautiful heritage necklace featuring beads and findings that suggest craftsmanship from a bygone era. Whether vintage or antique, this piece carries the energy of the hands that made it and the necks that wore it. A truly special find for those who appreciate jewellery with soul.',
                'short_description' => 'A beautiful heritage necklace with beads and findings from a bygone era.',
                'price' => 48.00,
                'sku' => 'NORA-JWL-010',
                'stock_quantity' => 1,
                'origin_type' => 'other',
                'origin_country' => 'Middle East (estimated)',
                'artisan_name' => null,
                'product_story' => 'This necklace was found among a collection of personal jewellery. Its style and materials suggest it may be several decades old.',
                'materials_used' => 'Mixed beads, metal findings, clasp',
                'handmade_technique' => 'Hand-strung',
                'care_instructions' => 'Store flat or hung. Avoid contact with perfume or chemicals.',
                'estimated_preparation_time' => '1-2 days',
                'estimated_shipping_time' => '7-14 business days',
                'is_one_of_a_kind' => true,
                'gift_wrapping_available' => true,
                'is_featured' => true,
                'dimensions' => 'Approx. 45cm length',
                'weight' => 0.03,
                'color_palette' => 'Mixed earth-tone beads, brass findings',
                'color_primary' => 'Earth Tones',
                'color_secondary' => 'Brass',
                'condition' => 'Good — all beads intact, clasp functional',
                'age_estimate' => 'Vintage (several decades estimated)',
                'style_notes' => 'Hand-strung with varied bead shapes and sizes',
                'height_cm' => 1,
                'width_cm' => 45,
                'depth_cm' => 1,
                'categories' => ['watches-jewellery'],
                'collections' => ['gifts-with-a-story'],
                'image_path' => 'images/nora/products/product-10.jpeg',
            ],
            [
                'name' => 'Artisan Ring',
                'slug' => 'artisan-ring',
                'description' => 'A unique artisan ring with character and charm. This pre-loved piece shows the marks of its previous life — gentle scratches and a warmth that only comes from being worn with love. A beautiful statement piece for someone who values individuality over mass production.',
                'short_description' => 'A unique artisan ring with character — pre-loved and full of warmth.',
                'price' => 32.00,
                'sku' => 'NORA-JWL-011',
                'stock_quantity' => 1,
                'origin_type' => 'other',
                'origin_country' => 'Middle East (estimated)',
                'artisan_name' => null,
                'product_story' => 'This ring was part of a personal jewellery collection. Its unique design suggests it was made by an independent artisan.',
                'materials_used' => 'Metal alloy or silver-tone',
                'handmade_technique' => 'Cast or hand-formed',
                'care_instructions' => 'Polish gently with a soft cloth. Remove before washing hands.',
                'estimated_preparation_time' => '1-2 days',
                'estimated_shipping_time' => '7-14 business days',
                'is_one_of_a_kind' => true,
                'gift_wrapping_available' => true,
                'is_featured' => false,
                'dimensions' => 'Adjustable, approx. 2cm Ø',
                'weight' => 0.01,
                'color_palette' => 'Silver-tone with subtle oxidation',
                'color_primary' => 'Silver',
                'color_secondary' => 'Oxidized',
                'condition' => 'Good — gentle wear marks consistent with use',
                'age_estimate' => 'Artisan-made, likely modern',
                'style_notes' => 'Unique handmade form with organic character',
                'height_cm' => 1,
                'width_cm' => 2,
                'depth_cm' => 2,
                'categories' => ['watches-jewellery'],
                'collections' => [],
                'image_path' => 'images/nora/products/product-11.jpeg',
            ],

            // ── Collectibles & Commemorative (product-12 to product-14) ──
            [
                'name' => 'Commemorative Collector Plate',
                'slug' => 'commemorative-collector-plate',
                'description' => 'A commemorative collector plate with detailed imagery and text marking a special event or heritage. These plates were once prized display pieces, often given as gifts or collected over years. A wonderful find for collectors and heritage enthusiasts.',
                'short_description' => 'A commemorative collector plate marking a special heritage or event.',
                'price' => 58.00,
                'sku' => 'NORA-COL-012',
                'stock_quantity' => 1,
                'origin_type' => 'other',
                'origin_country' => 'Middle East (estimated)',
                'artisan_name' => null,
                'product_story' => 'Commemorative plates were once a popular way to mark important occasions and celebrate cultural heritage. This piece was carefully preserved in a display cabinet.',
                'materials_used' => 'Fine ceramic with decorative print',
                'handmade_technique' => 'Printed and hand-finished',
                'care_instructions' => 'Display only. Dust with a soft cloth. Handle with care.',
                'estimated_preparation_time' => '1-2 days',
                'estimated_shipping_time' => '7-14 business days',
                'is_one_of_a_kind' => true,
                'gift_wrapping_available' => true,
                'is_featured' => true,
                'dimensions' => 'Approx. 25cm Ø × 3cm H',
                'weight' => 0.60,
                'color_palette' => 'White ceramic base, full-colour commemorative print',
                'color_primary' => 'White',
                'color_secondary' => 'Multi',
                'condition' => 'Excellent — display piece, no wear',
                'age_estimate' => 'Commemorative edition',
                'style_notes' => 'Detailed printed scene with gold-edged border',
                'height_cm' => 3,
                'width_cm' => 25,
                'depth_cm' => 25,
                'categories' => ['collectibles-commemorative'],
                'collections' => ['gifts-with-a-story'],
                'image_path' => 'images/nora/products/product-12.jpeg',
            ],
            [
                'name' => 'Antique Decorative Ornament',
                'slug' => 'antique-decorative-ornament',
                'description' => 'An antique decorative ornament that has survived the passage of time with grace. Its craftsmanship speaks of an era when objects were made to last and to be treasured. A meaningful addition to any collection of special objects.',
                'short_description' => 'An antique decorative ornament — a survivor of time, crafted to be treasured.',
                'price' => 40.00,
                'sku' => 'NORA-COL-013',
                'stock_quantity' => 1,
                'origin_type' => 'other',
                'origin_country' => 'Middle East (estimated)',
                'artisan_name' => null,
                'product_story' => 'This ornament has been passed between collectors and admirers. Its age is difficult to determine precisely, but its quality is unmistakable.',
                'materials_used' => 'Mixed materials — ceramic, metal, or wood',
                'handmade_technique' => 'Hand-crafted',
                'care_instructions' => 'Display in a protected area. Handle with clean, dry hands.',
                'estimated_preparation_time' => '1-2 days',
                'estimated_shipping_time' => '7-14 business days',
                'is_one_of_a_kind' => true,
                'gift_wrapping_available' => true,
                'is_featured' => false,
                'dimensions' => 'Approx. 15cm H × 10cm W',
                'weight' => 0.35,
                'color_palette' => 'Mixed — aged patina, warm tones',
                'color_primary' => 'Patina',
                'color_secondary' => 'Warm',
                'condition' => 'Fair to Good — age-appropriate wear',
                'age_estimate' => 'Antique (age difficult to determine precisely)',
                'style_notes' => 'Detailed craftsmanship with aged character',
                'height_cm' => 15,
                'width_cm' => 10,
                'depth_cm' => 10,
                'categories' => ['collectibles-commemorative'],
                'collections' => [],
                'image_path' => 'images/nora/products/product-13.jpeg',
            ],
            [
                'name' => 'Heritage Collectible Piece',
                'slug' => 'heritage-collectible-piece',
                'description' => 'A heritage collectible piece that embodies the craftsmanship and cultural spirit of its origin. Whether a small sculpture, a carved figure, or a decorative item, it carries within it the story of the hands that shaped it and the culture it represents.',
                'short_description' => 'A heritage collectible piece embodying craftsmanship and cultural spirit.',
                'price' => 46.00,
                'sku' => 'NORA-COL-014',
                'stock_quantity' => 1,
                'origin_type' => 'other',
                'origin_country' => 'Middle East (estimated)',
                'artisan_name' => null,
                'product_story' => 'This collectible was chosen for its ability to tell a story without words. Its form and finish speak to a tradition of making beautiful things by hand.',
                'materials_used' => 'Ceramic, wood, or mixed media',
                'handmade_technique' => 'Hand-crafted',
                'care_instructions' => 'Display on a stable surface. Dust regularly.',
                'estimated_preparation_time' => '1-2 days',
                'estimated_shipping_time' => '7-14 business days',
                'is_one_of_a_kind' => true,
                'gift_wrapping_available' => true,
                'is_featured' => false,
                'dimensions' => 'Approx. 18cm H × 12cm W',
                'weight' => 0.50,
                'color_palette' => 'Earthy tones, natural finishes',
                'color_primary' => 'Earth',
                'color_secondary' => 'Natural',
                'condition' => 'Good — well preserved',
                'age_estimate' => 'Traditional craft piece',
                'style_notes' => 'Hand-crafted form with cultural significance',
                'height_cm' => 18,
                'width_cm' => 12,
                'depth_cm' => 12,
                'categories' => ['collectibles-commemorative'],
                'collections' => ['gifts-with-a-story'],
                'image_path' => 'images/nora/products/product-14.jpeg',
            ],

            // ── Accessories & Handbags (product-15 to product-17) ──────
            [
                'name' => 'Vintage Handbag',
                'slug' => 'vintage-handbag',
                'description' => 'A vintage handbag with classic lines and a timeless silhouette. The leather has softened beautifully with age, developing a patina that only time can create. A functional piece of fashion history — ready to carry its next owner\'s essentials with style.',
                'short_description' => 'A vintage handbag with classic lines and a beautiful aged patina.',
                'price' => 55.00,
                'sku' => 'NORA-ACC-015',
                'stock_quantity' => 1,
                'origin_type' => 'other',
                'origin_country' => 'Middle East (estimated)',
                'artisan_name' => null,
                'product_story' => 'This handbag was carried with care for many years. The softening of the material and the gentle wear at the handles tell the story of daily use and faithful companionship.',
                'materials_used' => 'Leather or faux leather, metal hardware',
                'handmade_technique' => 'Manufactured, hand-finished details',
                'care_instructions' => 'Store stuffed to maintain shape. Condition leather periodically if applicable.',
                'estimated_preparation_time' => '1-2 days',
                'estimated_shipping_time' => '7-14 business days',
                'is_one_of_a_kind' => true,
                'gift_wrapping_available' => true,
                'is_featured' => true,
                'dimensions' => 'Approx. 28cm W × 20cm H × 10cm D',
                'weight' => 0.45,
                'color_palette' => 'Rich brown leather, brass hardware',
                'color_primary' => 'Brown',
                'color_secondary' => 'Brass',
                'condition' => 'Good — softened with age, beautiful patina',
                'age_estimate' => 'Late 20th century (estimated)',
                'style_notes' => 'Classic structured silhouette with aged leather character',
                'height_cm' => 20,
                'width_cm' => 28,
                'depth_cm' => 10,
                'categories' => ['accessories-handbags'],
                'collections' => ['gifts-with-a-story'],
                'image_path' => 'images/nora/products/product-15.jpeg',
            ],
            [
                'name' => 'Classic Vintage Accessory',
                'slug' => 'classic-vintage-accessory',
                'description' => 'A classic vintage accessory that bridges the gap between fashion and function. Whether a belt, scarf, brooch, or small leather good, this piece has the quality and character that modern fast fashion cannot replicate. A small treasure with big personality.',
                'short_description' => 'A classic vintage accessory — a small treasure with big personality.',
                'price' => 25.00,
                'sku' => 'NORA-ACC-016',
                'stock_quantity' => 1,
                'origin_type' => 'other',
                'origin_country' => 'Middle East (estimated)',
                'artisan_name' => null,
                'product_story' => 'Vintage accessories are often the most personal of pre-loved items. This piece was worn and loved, and now it awaits its next chapter.',
                'materials_used' => 'Mixed materials — leather, fabric, or metal',
                'handmade_technique' => 'Manufactured with quality materials',
                'care_instructions' => 'Follow material-specific care instructions.',
                'estimated_preparation_time' => '1-2 days',
                'estimated_shipping_time' => '7-14 business days',
                'is_one_of_a_kind' => true,
                'gift_wrapping_available' => true,
                'is_featured' => false,
                'dimensions' => 'Varies — small accessory',
                'weight' => 0.05,
                'color_palette' => 'Mixed materials, vintage tones',
                'color_primary' => 'Mixed',
                'color_secondary' => 'Vintage',
                'condition' => 'Good — pre-loved with character',
                'age_estimate' => 'Vintage',
                'style_notes' => 'Quality materials with timeless appeal',
                'height_cm' => 5,
                'width_cm' => 15,
                'depth_cm' => 5,
                'categories' => ['accessories-handbags'],
                'collections' => [],
                'image_path' => 'images/nora/products/product-16.jpeg',
            ],
            [
                'name' => 'Timeless Pre-Loved Piece',
                'slug' => 'timeless-pre-loved-piece',
                'description' => 'A timeless pre-loved piece that defies easy categorisation. It may be an accessory, a small decorative object, or a wearable item — what matters is the feeling it evokes. Some things are simply beautiful, and this is one of them.',
                'short_description' => 'A timeless pre-loved piece — simply beautiful, ready for a new story.',
                'price' => 30.00,
                'sku' => 'NORA-ACC-017',
                'stock_quantity' => 1,
                'origin_type' => 'other',
                'origin_country' => 'Middle East (estimated)',
                'artisan_name' => null,
                'product_story' => 'The beauty of pre-loved items is that they come with an invisible history. This piece was chosen because it spoke to us — and we hope it will speak to you too.',
                'materials_used' => 'Mixed materials',
                'handmade_technique' => 'Varied',
                'care_instructions' => 'Handle with care. Clean as appropriate for the material.',
                'estimated_preparation_time' => '1-2 days',
                'estimated_shipping_time' => '7-14 business days',
                'is_one_of_a_kind' => true,
                'gift_wrapping_available' => true,
                'is_featured' => false,
                'dimensions' => 'Varies — small to medium',
                'weight' => 0.20,
                'color_palette' => 'Mixed materials, warm tones',
                'color_primary' => 'Warm',
                'color_secondary' => 'Mixed',
                'condition' => 'Good — pre-loved with individual character',
                'age_estimate' => 'Various',
                'style_notes' => 'Defies categorisation — chosen for its beauty',
                'height_cm' => 10,
                'width_cm' => 15,
                'depth_cm' => 10,
                'categories' => ['accessories-handbags'],
                'collections' => [],
                'image_path' => 'images/nora/products/product-17.jpeg',
            ],
        ];

        foreach ($products as $productData) {
            $categorySlugs = $productData['categories'] ?? [];
            $collectionSlugs = $productData['collections'] ?? [];
            $imagePath = $productData['image_path'] ?? null;
            unset($productData['categories'], $productData['collections'], $productData['image_path']);

            $product = Product::create([
                ...$productData,
                'is_active' => true,
            ]);

            // Attach categories
            $categories = Category::whereIn('slug', $categorySlugs)->get();
            $product->categories()->attach($categories);

            // Attach collections
            if (!empty($collectionSlugs)) {
                $collections = Collection::whereIn('slug', $collectionSlugs)->get();
                $product->collections()->attach($collections);
            }

            // Create product image
            if ($imagePath) {
                ProductImage::create([
                    'product_id' => $product->id,
                    'path' => $imagePath,
                    'alt_text' => $productData['name'],
                    'sort_order' => 0,
                    'is_primary' => true,
                ]);
            }
        }
    }
}
